/*
================================================================================
STREAM CIPHER TESTBENCH
================================================================================
Authors: Federico Pucci, Giovanni Del Bianco
Date: may/2026
Description:
    This testbench automates the verification of the Stream Cipher Top-Level.
    It reads input stimuli and expected results from external .tv files 
    (generated by the Python Golden Model) and compares them with the 
    actual hardware output.

    Verification Flow:
    1. Apply Asynchronous Reset.
    2. Pulse 'new_msg' to load the secret Key K.
    3. Read hex values from .tv files.
    4. Use a handshake (in_valid/out_ready) to process each byte.
    5. Report [OK] or [FAILED] for each byte.
================================================================================
*/

`timescale 1ns/1ps

module tb_stream_cipher();

    // --- Local Signals (Interconnects to the DUT) ---
    logic        clk;
    logic        rst_n;
    logic        new_msg;
    logic        in_valid;
    logic [7:0] key_in;
    logic [7:0] data_in;
    logic        out_ready;
    logic [7:0] data_out;

    // --- File Handling Variables ---
    int fd_in, fd_exp;      // File descriptors for input and expected files
    logic [7:0] val_in, val_exp;
    int status;

    // --- Design Under Test (DUT) Instance ---
    stream_cipher_top dut (
        .clk       (clk),
        .rst_n     (rst_n),
        .new_msg   (new_msg),
        .in_valid  (in_valid),
        .key_in    (key_in),
        .data_in   (data_in),
        .out_ready (out_ready),
        .data_out  (data_out)
    );

    // --- Clock Generator (100MHz) ---
    // #5 means 5ns high, 5ns low -> 10ns period = 100MHz
    always #5 clk = ~clk;

    initial begin
        // --- 1. Initialization ---
        clk = 0;
        rst_n = 0;          // Start in reset
        new_msg = 0;
        in_valid = 0;
        key_in = 8'd10;     // Secret Key K = 10 (Must match the Python script key) EDITABLE
        data_in = 0;

        // --- 2. Asynchronous Reset Release ---
        #20 rst_n = 1;      // Release reset after 20ns
        repeat(2) @(posedge clk); // Wait 2 clock cycles

        // --- 3. Open Test Vector Files ---
        // Make sure these files exist in the modelsim/tv/ directory EDIT THE FILES IF YOU WANT TO ENCRYPTION OR DECYPTION
        fd_in  = $fopen("tv/Hello_input.tv", "r");
        fd_exp = $fopen("tv/Hello_expected.tv", "r");

        if (fd_in == 0 || fd_exp == 0) begin
            $display("ERROR: .tv files not found in modelsim/tv/ folder!");
            $finish;
        end

        $display("--- Starting Unified Simulation with .tv Files ---");

        // --- 4. Loading the Key ---
        @(posedge clk);
        new_msg = 1;        // Pulse new_msg to trigger the 'load_en' in the FSM
        @(posedge clk);
        new_msg = 0;
        // Wait one cycle for the counter to stabilize on Key K before sending data
        @(posedge clk);

        // --- 5. Main Simulation Loop ---
        while (!$feof(fd_in)) begin
            // Read Hex values from the files
            status = $fscanf(fd_in, "%h\n", val_in);
            status = $fscanf(fd_exp, "%h\n", val_exp);

            if (status != -1) begin
                // Send the byte and verify the response using the task
                send_and_check(val_in, val_exp);
            end
        end

        // --- 6. Finalize ---
        $display("--- Test Completed Successfully ---");
        $fclose(fd_in);
        $fclose(fd_exp);
        $stop;
    end

    // --- Verification Task: Handshake and Comparison ---
    task send_and_check(input logic [7:0] bin, input logic [7:0] bexp);
        @(posedge clk);     // Align with clock
        data_in = bin;      // Put data on the bus
        in_valid = 1;       // Signal that data is valid
        
        // Wait for the Hardware (FSM) to signal that the result is ready
        // This handles the ST_ROM_WAIT latency automatically.
        wait (out_ready == 1);
        
        // IMMEDIATE SAMPLING:
        // We check the output immediately while out_ready is high,
        // before the next clock edge increments the counter.
        if (data_out !== bexp) begin
            $display("[FAILED] t=%t | In:%h | Out:%h | Expected:%h", $time, bin, data_out, bexp);
        end else begin
            $display("[OK] t=%t | In:%h -> Out:%h", $time, bin, data_out);
        end

        @(posedge clk);     // End of processing
        in_valid = 0;       // Pull valid low to complete handshake
        
        // Small pause to allow the FSM to return to IDLE
        repeat(1) @(posedge clk); 
    endtask

endmodule